# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cloudsecurity_pb2 as cloudsecurity__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cloudsecurity_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.login = channel.unary_unary(
                '/cloud.UserService/login',
                request_serializer=cloudsecurity__pb2.Request.SerializeToString,
                response_deserializer=cloudsecurity__pb2.Response.FromString,
                _registered_method=True)
        self.verifyOtp = channel.unary_unary(
                '/cloud.UserService/verifyOtp',
                request_serializer=cloudsecurity__pb2.Request.SerializeToString,
                response_deserializer=cloudsecurity__pb2.Response.FromString,
                _registered_method=True)
        self.register = channel.unary_unary(
                '/cloud.UserService/register',
                request_serializer=cloudsecurity__pb2.RegisterRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.Response.FromString,
                _registered_method=True)
        self.upload = channel.unary_unary(
                '/cloud.UserService/upload',
                request_serializer=cloudsecurity__pb2.UploadRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.Response.FromString,
                _registered_method=True)
        self.listFiles = channel.unary_unary(
                '/cloud.UserService/listFiles',
                request_serializer=cloudsecurity__pb2.UserRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.FileList.FromString,
                _registered_method=True)
        self.download = channel.unary_unary(
                '/cloud.UserService/download',
                request_serializer=cloudsecurity__pb2.DownloadRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.DownloadResponse.FromString,
                _registered_method=True)
        self.deleteFile = channel.unary_unary(
                '/cloud.UserService/deleteFile',
                request_serializer=cloudsecurity__pb2.DeleteRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.Response.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def verifyOtp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def upload(self, request, context):
        """NEW FILE OPERATIONS
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def download(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'login': grpc.unary_unary_rpc_method_handler(
                    servicer.login,
                    request_deserializer=cloudsecurity__pb2.Request.FromString,
                    response_serializer=cloudsecurity__pb2.Response.SerializeToString,
            ),
            'verifyOtp': grpc.unary_unary_rpc_method_handler(
                    servicer.verifyOtp,
                    request_deserializer=cloudsecurity__pb2.Request.FromString,
                    response_serializer=cloudsecurity__pb2.Response.SerializeToString,
            ),
            'register': grpc.unary_unary_rpc_method_handler(
                    servicer.register,
                    request_deserializer=cloudsecurity__pb2.RegisterRequest.FromString,
                    response_serializer=cloudsecurity__pb2.Response.SerializeToString,
            ),
            'upload': grpc.unary_unary_rpc_method_handler(
                    servicer.upload,
                    request_deserializer=cloudsecurity__pb2.UploadRequest.FromString,
                    response_serializer=cloudsecurity__pb2.Response.SerializeToString,
            ),
            'listFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.listFiles,
                    request_deserializer=cloudsecurity__pb2.UserRequest.FromString,
                    response_serializer=cloudsecurity__pb2.FileList.SerializeToString,
            ),
            'download': grpc.unary_unary_rpc_method_handler(
                    servicer.download,
                    request_deserializer=cloudsecurity__pb2.DownloadRequest.FromString,
                    response_serializer=cloudsecurity__pb2.DownloadResponse.SerializeToString,
            ),
            'deleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteFile,
                    request_deserializer=cloudsecurity__pb2.DeleteRequest.FromString,
                    response_serializer=cloudsecurity__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloud.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cloud.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.UserService/login',
            cloudsecurity__pb2.Request.SerializeToString,
            cloudsecurity__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def verifyOtp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.UserService/verifyOtp',
            cloudsecurity__pb2.Request.SerializeToString,
            cloudsecurity__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.UserService/register',
            cloudsecurity__pb2.RegisterRequest.SerializeToString,
            cloudsecurity__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def upload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.UserService/upload',
            cloudsecurity__pb2.UploadRequest.SerializeToString,
            cloudsecurity__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.UserService/listFiles',
            cloudsecurity__pb2.UserRequest.SerializeToString,
            cloudsecurity__pb2.FileList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def download(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.UserService/download',
            cloudsecurity__pb2.DownloadRequest.SerializeToString,
            cloudsecurity__pb2.DownloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.UserService/deleteFile',
            cloudsecurity__pb2.DeleteRequest.SerializeToString,
            cloudsecurity__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
