# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloudsecurity.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloudsecurity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63loudsecurity.proto\x12\x05\x63loud\"*\n\x07Request\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"D\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"\x1a\n\x08Response\x12\x0e\n\x06result\x18\x01 \x01(\t\"A\n\rUploadRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"\x1f\n\x0bUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\",\n\x08\x46ileList\x12\x11\n\tfilenames\x18\x01 \x03(\t\x12\r\n\x05sizes\x18\x02 \x03(\x03\"5\n\x0f\x44ownloadRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"A\n\x10\x44ownloadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06result\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"3\n\rDeleteRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t2\xef\x02\n\x0bUserService\x12(\n\x05login\x12\x0e.cloud.Request\x1a\x0f.cloud.Response\x12,\n\tverifyOtp\x12\x0e.cloud.Request\x1a\x0f.cloud.Response\x12\x33\n\x08register\x12\x16.cloud.RegisterRequest\x1a\x0f.cloud.Response\x12/\n\x06upload\x12\x14.cloud.UploadRequest\x1a\x0f.cloud.Response\x12\x30\n\tlistFiles\x12\x12.cloud.UserRequest\x1a\x0f.cloud.FileList\x12;\n\x08\x64ownload\x12\x16.cloud.DownloadRequest\x1a\x17.cloud.DownloadResponse\x12\x33\n\ndeleteFile\x12\x14.cloud.DeleteRequest\x1a\x0f.cloud.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloudsecurity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=30
  _globals['_REQUEST']._serialized_end=72
  _globals['_REGISTERREQUEST']._serialized_start=74
  _globals['_REGISTERREQUEST']._serialized_end=142
  _globals['_RESPONSE']._serialized_start=144
  _globals['_RESPONSE']._serialized_end=170
  _globals['_UPLOADREQUEST']._serialized_start=172
  _globals['_UPLOADREQUEST']._serialized_end=237
  _globals['_USERREQUEST']._serialized_start=239
  _globals['_USERREQUEST']._serialized_end=270
  _globals['_FILELIST']._serialized_start=272
  _globals['_FILELIST']._serialized_end=316
  _globals['_DOWNLOADREQUEST']._serialized_start=318
  _globals['_DOWNLOADREQUEST']._serialized_end=371
  _globals['_DOWNLOADRESPONSE']._serialized_start=373
  _globals['_DOWNLOADRESPONSE']._serialized_end=438
  _globals['_DELETEREQUEST']._serialized_start=440
  _globals['_DELETEREQUEST']._serialized_end=491
  _globals['_USERSERVICE']._serialized_start=494
  _globals['_USERSERVICE']._serialized_end=861
# @@protoc_insertion_point(module_scope)
